### ISSUE TITLE
Problem: RTX PRO 6000 Blackwell(MAX-Q) with Isaac Manipulator Reference Workflows with Isaac Sim

### ISSUE THREAD

**Issue by mat-macnica** [NVIDIA-ISAAC-ROS/isaac_manipulator#13]
Hello,

I try to run Issac_Manipulator sample(pose_to_pose) like below.
https://nvidia-isaac-ros.github.io/reference_workflows/isaac_manipulator/tutorials/tutorial_isaac_sim.html#build-isaac-ros-cumotion

I can success to run with RTX 6000ada GPU and IsaacSim4.2.0.
But I found Cuda error like below with RTX PRO 6000 Blackwell(MAX-Q).

Question:
  Are there any successful way to run this sample with RTX PRO 6000 Blackwell(MAX-Q) like below environment?

[Our Environment]
Isaac Sim Version:5.0.0-full(download&install below link) 
https://docs.isaacsim.omniverse.nvidia.com/latest/installation/download.html
Operating System:Ubuntu 22.04
GPU Information:NVIDIA RTX PRO 6000 Blackwell(MAX-Q)
CUDA : 12.8

I would appreciate if you tell us how to solve this problem.

[ERROR]
admin@nvidia-SYS-551A-T:/workspaces/isaac_ros-dev$ ros2 launch isaac_manipulator_pick_and_place isaac_sim_workflows.launch.py workflow_type:=pose_to_pose
[INFO] [launch]: All log files can be found below /home/admin/.ros/log/2025-09-01-16-56-13-161419-nvidia-SYS-551A-T-13555
[INFO] [launch]: Default logging verbosity is set to INFO
WARNING:root:Cannot infer URDF from `/workspaces/isaac_ros-dev/install/isaac_manipulator_pick_and_place/share/isaac_manipulator_pick_and_place`. -- using config/ur10e.urdf
WARNING:root:Cannot infer SRDF from `/workspaces/isaac_ros-dev/install/isaac_manipulator_pick_and_place/share/isaac_manipulator_pick_and_place`. -- using config/ur10e.srdf
WARNING:root:"File /workspaces/isaac_ros-dev/install/isaac_manipulator_pick_and_place/share/isaac_manipulator_pick_and_place/config/ur10e.urdf doesn't exist"
WARNING:root:The robot description will be loaded from /robot_description topic 
[INFO] [launch.user]: Loading the 'sim_test_bench' workspace. Ignoring the grid_center_m / grid_size_m parameters of cumotion and esdf visualizer.
[INFO] [launch.user]: Adding nodes [ /nvblox_node ] to container manipulator_container.
[INFO] [launch.user]: Enabling nvblox for '1' 'isaac_sim' cameras configured for the 'sim_test_bench' workspace.
[INFO] [component_container_mt-1]: process started with pid [13588]
[INFO] [robot_state_publisher-2]: process started with pid [13590]
[INFO] [joint_state_publisher-3]: process started with pid [13592]
[INFO] [cumotion_goal_set_planner_node-4]: process started with pid [13594]
[INFO] [robot_segmenter_node-5]: process started with pid [13596]
[INFO] [attach_object_server_node-6]: process started with pid [13598]
[INFO] [move_group-7]: process started with pid [13600]
[INFO] [rviz2-8]: process started with pid [13602]
[INFO] [joint_parser_node.py-9]: process started with pid [13604]
[INFO] [ros2_control_node-10]: process started with pid [13606]
[INFO] [spawner-11]: process started with pid [13608]
[INFO] [isaac_sim_gripper_action_server.py-12]: process started with pid [13610]
[INFO] [spawner-13]: process started with pid [13612]
[INFO] [pose_to_pose_node-14]: process started with pid [13614]
[robot_state_publisher-2] [INFO] [1756713373.913303154] [robot_state_publisher]: got segment base
[robot_state_publisher-2] [INFO] [1756713373.913450318] [robot_state_publisher]: got segment base_link
[robot_state_publisher-2] [INFO] [1756713373.913461701] [robot_state_publisher]: got segment base_link_inertia
[robot_state_publisher-2] [INFO] [1756713373.913468379] [robot_state_publisher]: got segment flange
[robot_state_publisher-2] [INFO] [1756713373.913474411] [robot_state_publisher]: got segment forearm_link
[robot_state_publisher-2] [INFO] [1756713373.913480237] [robot_state_publisher]: got segment ft_frame
[robot_state_publisher-2] [INFO] [1756713373.913486275] [robot_state_publisher]: got segment grasp_frame
[robot_state_publisher-2] [INFO] [1756713373.913492494] [robot_state_publisher]: got segment gripper_frame
[robot_state_publisher-2] [INFO] [1756713373.913504276] [robot_state_publisher]: got segment left_inner_finger
[robot_state_publisher-2] [INFO] [1756713373.913510264] [robot_state_publisher]: got segment left_inner_finger_pad
[robot_state_publisher-2] [INFO] [1756713373.913516380] [robot_state_publisher]: got segment left_inner_knuckle
[robot_state_publisher-2] [INFO] [1756713373.913522146] [robot_state_publisher]: got segment left_outer_finger
[robot_state_publisher-2] [INFO] [1756713373.913527958] [robot_state_publisher]: got segment left_outer_knuckle
[robot_state_publisher-2] [INFO] [1756713373.913533403] [robot_state_publisher]: got segment right_inner_finger
[robot_state_publisher-2] [INFO] [1756713373.913539028] [robot_state_publisher]: got segment right_inner_finger_pad
[robot_state_publisher-2] [INFO] [1756713373.913545124] [robot_state_publisher]: got segment right_inner_knuckle
[robot_state_publisher-2] [INFO] [1756713373.913551096] [robot_state_publisher]: got segment right_outer_finger
[robot_state_publisher-2] [INFO] [1756713373.913556673] [robot_state_publisher]: got segment right_outer_knuckle
[robot_state_publisher-2] [INFO] [1756713373.913562362] [robot_state_publisher]: got segment robotiq_140_base_link
[robot_state_publisher-2] [INFO] [1756713373.913568380] [robot_state_publisher]: got segment robotiq_base_link
[robot_state_publisher-2] [INFO] [1756713373.913573900] [robot_state_publisher]: got segment shoulder_link
[robot_state_publisher-2] [INFO] [1756713373.913579348] [robot_state_publisher]: got segment tool0
[robot_state_publisher-2] [INFO] [1756713373.913585111] [robot_state_publisher]: got segment upper_arm_link
[robot_state_publisher-2] [INFO] [1756713373.913590819] [robot_state_publisher]: got segment world
[robot_state_publisher-2] [INFO] [1756713373.913596576] [robot_state_publisher]: got segment wrist_1_link
[robot_state_publisher-2] [INFO] [1756713373.913602166] [robot_state_publisher]: got segment wrist_2_link
[robot_state_publisher-2] [INFO] [1756713373.913607906] [robot_state_publisher]: got segment wrist_3_link
[ros2_control_node-10] [INFO] [1756713373.926194407] [controller_manager]: Subscribing to '~/robot_description' topic for robot description file.
[ros2_control_node-10] [INFO] [1756713373.927174004] [controller_manager]: update rate is 100 Hz
[ros2_control_node-10] [INFO] [1756713373.927207883] [controller_manager]: Spawning controller_manager RT thread with scheduler priority: 50
[ros2_control_node-10] [WARN] [1756713373.927329165] [controller_manager]: No real-time kernel detected on this system. See [https://control.ros.org/master/doc/ros2_control/controller_manager/doc/userdoc.html] for details on how to enable realtime scheduling.
[ros2_control_node-10] [INFO] [1756713373.937519701] [controller_manager]: Received robot description file.
[ros2_control_node-10] [INFO] [1756713373.938141923] [resource_manager]: Loading hardware 'ur_ros2_control_sim' 
[ros2_control_node-10] [INFO] [1756713373.940338577] [resource_manager]: Initialize hardware 'ur_ros2_control_sim' 
[rviz2-8] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-admin'
[move_group-7] [INFO] [1756713373.942416364] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0 seconds
[move_group-7] [INFO] [1756713373.942511571] [moveit_robot_model.robot_model]: Loading robot model 'robotiq_gripper'...
[move_group-7] [INFO] [1756713373.942521981] [moveit_robot_model.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ros2_control_node-10] [INFO] [1756713373.948514302] [resource_manager]: Successful initialization of hardware 'ur_ros2_control_sim'
[ros2_control_node-10] [INFO] [1756713373.948636881] [resource_manager]: 'configure' hardware 'ur_ros2_control_sim' 
[ros2_control_node-10] [INFO] [1756713373.948647136] [resource_manager]: Successful 'configure' of hardware 'ur_ros2_control_sim'
[ros2_control_node-10] [INFO] [1756713373.948654718] [resource_manager]: 'activate' hardware 'ur_ros2_control_sim' 
[ros2_control_node-10] [INFO] [1756713373.948658862] [resource_manager]: Successful 'activate' of hardware 'ur_ros2_control_sim'
[move_group-7] [INFO] [1756713374.041600209] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-7] [INFO] [1756713374.041833209] [moveit.ros_planning_interface.moveit_cpp]: Listening to 'joint_states' for joint states
[move_group-7] [INFO] [1756713374.044255169] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[move_group-7] [INFO] [1756713374.045353689] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[move_group-7] [INFO] [1756713374.045370315] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[move_group-7] [INFO] [1756713374.046907075] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/planning_scene'
[move_group-7] [INFO] [1756713374.046934797] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-7] [INFO] [1756713374.048341965] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'collision_object'
[move_group-7] [INFO] [1756713374.050085279] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-7] [WARN] [1756713374.052595982] [moveit.ros.occupancy_map_monitor.middleware_handle]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-7] [ERROR] [1756713374.052620947] [moveit.ros.occupancy_map_monitor.middleware_handle]: No 3D sensor plugin(s) defined for octomap updates
[move_group-7] [INFO] [1756713374.065863792] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'isaac_ros_cumotion'
[move_group-7] [WARN] [1756713374.079089559] [pluginlib.ClassLoader]: given plugin name 'libisaac_ros_cumotion_moveit' should be 'isaac_ros_cumotion_moveit' for better portability
[move_group-7] [INFO] [1756713374.123145378] [moveit.ros_planning.planning_pipeline]: Using planning interface 'Generate minimum-jerk trajectories using NVIDIA Isaac ROS cuMotion'
[move_group-7] [INFO] [1756713374.133821587] [moveit_ros.fix_workspace_bounds]: Param 'isaac_ros_cumotion.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-7] [INFO] [1756713374.133872585] [moveit_ros.fix_start_state_bounds]: Param 'isaac_ros_cumotion.start_state_max_bounds_error' was set to 0.100000
[move_group-7] [INFO] [1756713374.133879684] [moveit_ros.fix_start_state_bounds]: Param 'isaac_ros_cumotion.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-7] [INFO] [1756713374.133894302] [moveit_ros.fix_start_state_collision]: Param 'isaac_ros_cumotion.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-7] [INFO] [1756713374.133901563] [moveit_ros.fix_start_state_collision]: Param 'isaac_ros_cumotion.jiggle_fraction' was not set. Using default value: 0.020000
[move_group-7] [INFO] [1756713374.133907511] [moveit_ros.fix_start_state_collision]: Param 'isaac_ros_cumotion.max_sampling_attempts' was not set. Using default value: 100
[move_group-7] [INFO] [1756713374.133921452] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-7] [INFO] [1756713374.133926352] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-7] [INFO] [1756713374.133930159] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-7] [INFO] [1756713374.133933980] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[move_group-7] [INFO] [1756713374.144467117] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'ompl'
[move_group-7] [INFO] [1756713374.148029474] [moveit.ros_planning.planning_pipeline]: Multiple planning plugins available. You should specify the '~planning_plugin' parameter. Using 'chomp_interface/CHOMPPlanner' for now.
[move_group-7] [INFO] [1756713374.154084995] [moveit.ros_planning.planning_pipeline]: Using planning interface 'CHOMP'
[move_group-7] [WARN] [1756713374.159468421] [moveit.ros_planning_interface.moveit_cpp]: Skipping duplicate entry for planning pipeline 'ompl'.
[move_group-7] [INFO] [1756713374.239238289] [moveit.plugins.moveit_simple_controller_manager]: Added FollowJointTrajectory controller for scaled_joint_trajectory_controller
[move_group-7] [INFO] [1756713374.252164143] [moveit.plugins.moveit_simple_controller_manager]: Added FollowJointTrajectory controller for joint_trajectory_controller
[move_group-7] [INFO] [1756713374.252804055] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[move_group-7] [INFO] [1756713374.252890056] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[move_group-7] [INFO] [1756713374.256406344] [moveit_ros.trajectory_execution_manager]: Trajectory execution is managing controllers
[move_group-7] [INFO] [1756713374.256434581] [move_group.move_group]: MoveGroup debug mode is ON
[move_group-7] [INFO] [1756713374.379691956] [move_group.move_group]: 
[move_group-7] 
[move_group-7] ********************************************************
[move_group-7] * MoveGroup using: 
[move_group-7] *     - ApplyPlanningSceneService
[move_group-7] *     - ClearOctomapService
[move_group-7] *     - ExecuteTaskSolution
[move_group-7] *     - CartesianPathService
[move_group-7] *     - ExecuteTrajectoryAction
[move_group-7] *     - GetPlanningSceneService
[move_group-7] *     - KinematicsService
[move_group-7] *     - MoveAction
[move_group-7] *     - MotionPlanService
[move_group-7] *     - QueryPlannersService
[move_group-7] *     - StateValidationService
[move_group-7] ********************************************************
[move_group-7] 
[move_group-7] [INFO] [1756713374.379753593] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context using planning plugin isaac_ros_cumotion_moveit/CumotionPlanner
[move_group-7] [INFO] [1756713374.379764684] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context initialization complete
[move_group-7] Loading 'move_group/ApplyPlanningSceneService'...
[move_group-7] Loading 'move_group/ClearOctomapService'...
[move_group-7] Loading 'move_group/ExecuteTaskSolutionCapability'...
[move_group-7] Loading 'move_group/MoveGroupCartesianPathService'...
[move_group-7] Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
[move_group-7] Loading 'move_group/MoveGroupGetPlanningSceneService'...
[move_group-7] Loading 'move_group/MoveGroupKinematicsService'...
[move_group-7] Loading 'move_group/MoveGroupMoveAction'...
[move_group-7] Loading 'move_group/MoveGroupPlanService'...
[move_group-7] Loading 'move_group/MoveGroupQueryPlannersService'...
[move_group-7] Loading 'move_group/MoveGroupStateValidationService'...
[move_group-7] 
[move_group-7] You can start planning now!
[move_group-7] 
[ros2_control_node-10] [INFO] [1756713374.597078193] [controller_manager]: Loading controller 'joint_state_broadcaster'
[joint_state_publisher-3] [INFO] [1756713374.597112003] [joint_state_publisher]: Waiting for robot_description to be published on the robot_description topic...
[component_container_mt-1] WARNING: Logging before InitGoogleLogging() is written to STDERR
[component_container_mt-1] I0901 16:56:14.617358 13641 block_memory_pool_impl.h:65] Expanding the memory pool with 2048 blocks. Number of allocated blocks: 2048
[ros2_control_node-10] [INFO] [1756713374.659628976] [controller_manager]: Loading controller 'scaled_joint_trajectory_controller'
[ros2_control_node-10] [WARN] [1756713374.674958408] [scaled_joint_trajectory_controller]: [Deprecated]: "allow_nonzero_velocity_at_trajectory_end" is set to true. The default behavior will change to false.
[spawner-13] [INFO] [1756713374.675432567] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[ros2_control_node-10] [INFO] [1756713374.729038972] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ros2_control_node-10] [INFO] [1756713374.729195044] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[spawner-11] [INFO] [1756713374.801597279] [spawner_scaled_joint_trajectory_controller]: Loaded scaled_joint_trajectory_controller
[ros2_control_node-10] [INFO] [1756713374.922794021] [controller_manager]: Configuring controller 'scaled_joint_trajectory_controller'
[ros2_control_node-10] [INFO] [1756713374.923043830] [scaled_joint_trajectory_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[ros2_control_node-10] [INFO] [1756713374.923072396] [scaled_joint_trajectory_controller]: Command interfaces are [position] and state interfaces are [position velocity].
[ros2_control_node-10] [INFO] [1756713374.923100228] [scaled_joint_trajectory_controller]: Using 'splines' interpolation method.
[spawner-13] [INFO] [1756713374.923604580] [spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[ros2_control_node-10] [INFO] [1756713374.935564905] [scaled_joint_trajectory_controller]: Controller state will be published at 50.00 Hz.
[ros2_control_node-10] [INFO] [1756713374.950234032] [scaled_joint_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
[rviz2-8] [INFO] [1756713375.022015556] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-8] [INFO] [1756713375.022209836] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-8] [INFO] [1756713375.095780764] [rviz2]: Stereo is NOT SUPPORTED
[spawner-11] [INFO] [1756713375.098902414] [spawner_scaled_joint_trajectory_controller]: Configured and activated scaled_joint_trajectory_controller
[INFO] [spawner-13]: process has finished cleanly [pid 13612]
[rviz2-8] [INFO] [1756713375.186945113] [rviz2]: Connected on namespace: /end_effector_marker
[INFO] [spawner-11]: process has finished cleanly [pid 13608]
[rviz2-8] [INFO] [1756713375.730996949] [rviz2]: Stereo is NOT SUPPORTED
[pose_to_pose_node-14] [INFO] [1756713376.084000038] [pose_to_pose_node]: Server move_action not available! Waiting...
[pose_to_pose_node-14] [INFO] [1756713377.089923465] [pose_to_pose_node]: Server move_action not available! Waiting...
[move_group-7] [INFO] [1756713377.618163012] [moveit_move_group_default_capabilities.move_action_capability]: Received request
[move_group-7] [INFO] [1756713377.618406640] [moveit_move_group_default_capabilities.move_action_capability]: executing..
[move_group-7] [INFO] [1756713377.618562252] [moveit_move_group_default_capabilities.move_action_capability]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[move_group-7] [WARN] [1756713377.618583784] [moveit_move_group_capabilities_base.move_group_capability]: Execution of motions should always start at the robot's current state. Ignoring the state supplied as start state in the motion planning request
[move_group-7] [WARN] [1756713377.618591478] [moveit_move_group_capabilities_base.move_group_capability]: Execution of motions should always start at the robot's current state. Ignoring the state supplied as difference in the planning scene diff
[move_group-7] [INFO] [1756713377.618606601] [moveit_ros.plan_execution]: Planning attempt 1 of at most 1
[move_group-7] [INFO] [1756713377.618616239] [moveit_move_group_capabilities_base.move_group_capability]: Using planning pipeline 'isaac_ros_cumotion'
[move_group-7] [INFO] [1756713377.619171412] [move_group]: Planning trajectory
[pose_to_pose_node-14] [INFO] [1756713377.620756447] [pose_to_pose_node]: Planning Goal request accepted!
[robot_segmenter_node-5] /usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:287: UserWarning: 
[robot_segmenter_node-5] NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition with CUDA capability sm_120 is not compatible with the current PyTorch installation.
[robot_segmenter_node-5] The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
[robot_segmenter_node-5] If you want to use the NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
[robot_segmenter_node-5] 
[robot_segmenter_node-5]   warnings.warn(
[cumotion_goal_set_planner_node-4] /usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:287: UserWarning: 
[cumotion_goal_set_planner_node-4] NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition with CUDA capability sm_120 is not compatible with the current PyTorch installation.
[cumotion_goal_set_planner_node-4] The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
[cumotion_goal_set_planner_node-4] If you want to use the NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
[cumotion_goal_set_planner_node-4] 
[cumotion_goal_set_planner_node-4]   warnings.warn(
[robot_segmenter_node-5] Traceback (most recent call last):
[robot_segmenter_node-5]   File "/workspaces/isaac_ros-dev/install/isaac_ros_cumotion/lib/isaac_ros_cumotion/robot_segmenter_node", line 33, in <module>
[robot_segmenter_node-5]     sys.exit(load_entry_point('isaac-ros-cumotion', 'console_scripts', 'robot_segmenter_node')())
[robot_segmenter_node-5]   File "/workspaces/isaac_ros-dev/install/isaac_ros_cumotion/lib/isaac_ros_cumotion/robot_segmenter_node", line 25, in importlib_load_entry_point
[robot_segmenter_node-5]     return next(matches).load()
[robot_segmenter_node-5]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
[robot_segmenter_node-5]     module = import_module(match.group('module'))
[robot_segmenter_node-5]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[robot_segmenter_node-5]     return _bootstrap._gcd_import(name[level:], package, level)
[robot_segmenter_node-5]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[robot_segmenter_node-5]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[robot_segmenter_node-5]   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
[robot_segmenter_node-5]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[robot_segmenter_node-5]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[robot_segmenter_node-5]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[robot_segmenter_node-5]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[robot_segmenter_node-5]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[robot_segmenter_node-5]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[robot_segmenter_node-5]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[robot_segmenter_node-5]   File "/workspaces/isaac_ros-dev/build/isaac_ros_cumotion/isaac_ros_cumotion/__init__.py", line 17, in <module>
[robot_segmenter_node-5]     from .cumotion_goal_set_client import CumotionGoalSetClient
[robot_segmenter_node-5]   File "/workspaces/isaac_ros-dev/build/isaac_ros_cumotion/isaac_ros_cumotion/cumotion_goal_set_client.py", line 10, in <module>
[robot_segmenter_node-5]     from curobo.wrap.reacher.motion_gen import MotionGenPlanConfig
[robot_segmenter_node-5]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/wrap/reacher/motion_gen.py", line 1411, in <module>
[robot_segmenter_node-5]     class MotionGen(MotionGenConfig):
[robot_segmenter_node-5]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/wrap/reacher/motion_gen.py", line 4189, in MotionGen
[robot_segmenter_node-5]     grasp_approach_offset: Pose = Pose.from_list([0, 0, -0.15, 1, 0, 0, 0]),
[robot_segmenter_node-5]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/types/math.py", line 228, in from_list
[robot_segmenter_node-5]     return Pose(position=position, quaternion=quaternion)
[robot_segmenter_node-5]   File "<string>", line 10, in __init__
[robot_segmenter_node-5]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/types/math.py", line 85, in __post_init__
[robot_segmenter_node-5]     self.quaternion = normalize_quaternion(self.quaternion)
[robot_segmenter_node-5] RuntimeError: The following operation failed in the TorchScript interpreter.
[robot_segmenter_node-5] Traceback of TorchScript (most recent call last):
[robot_segmenter_node-5]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/types/math.py", line 533, in normalize_quaternion
[robot_segmenter_node-5] @get_torch_jit_decorator()
[robot_segmenter_node-5] def normalize_quaternion(in_quaternion: torch.Tensor) -> torch.Tensor:
[robot_segmenter_node-5]     k = torch.sign(in_quaternion[..., 0:1])
[robot_segmenter_node-5]         ~~~~~~~~~~ <--- HERE
[robot_segmenter_node-5]     # NOTE: torch sign returns 0 as sign value when value is 0.0
[robot_segmenter_node-5]     k = torch.where(k == 0, 1.0, k)
[robot_segmenter_node-5] RuntimeError: CUDA error: no kernel image is available for execution on the device
[robot_segmenter_node-5] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[robot_segmenter_node-5] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[robot_segmenter_node-5] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
[robot_segmenter_node-5] 
[robot_segmenter_node-5] 
[cumotion_goal_set_planner_node-4] Traceback (most recent call last):
[cumotion_goal_set_planner_node-4]   File "/workspaces/isaac_ros-dev/install/isaac_ros_cumotion/lib/isaac_ros_cumotion/cumotion_goal_set_planner_node", line 33, in <module>
[cumotion_goal_set_planner_node-4]     sys.exit(load_entry_point('isaac-ros-cumotion', 'console_scripts', 'cumotion_goal_set_planner_node')())
[cumotion_goal_set_planner_node-4]   File "/workspaces/isaac_ros-dev/install/isaac_ros_cumotion/lib/isaac_ros_cumotion/cumotion_goal_set_planner_node", line 25, in importlib_load_entry_point
[cumotion_goal_set_planner_node-4]     return next(matches).load()
[cumotion_goal_set_planner_node-4]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
[cumotion_goal_set_planner_node-4]     module = import_module(match.group('module'))
[cumotion_goal_set_planner_node-4]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[cumotion_goal_set_planner_node-4]     return _bootstrap._gcd_import(name[level:], package, level)
[cumotion_goal_set_planner_node-4]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[cumotion_goal_set_planner_node-4]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[cumotion_goal_set_planner_node-4]   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
[cumotion_goal_set_planner_node-4]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[cumotion_goal_set_planner_node-4]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[cumotion_goal_set_planner_node-4]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[cumotion_goal_set_planner_node-4]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[cumotion_goal_set_planner_node-4]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[cumotion_goal_set_planner_node-4]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[cumotion_goal_set_planner_node-4]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[cumotion_goal_set_planner_node-4]   File "/workspaces/isaac_ros-dev/build/isaac_ros_cumotion/isaac_ros_cumotion/__init__.py", line 17, in <module>
[cumotion_goal_set_planner_node-4]     from .cumotion_goal_set_client import CumotionGoalSetClient
[cumotion_goal_set_planner_node-4]   File "/workspaces/isaac_ros-dev/build/isaac_ros_cumotion/isaac_ros_cumotion/cumotion_goal_set_client.py", line 10, in <module>
[cumotion_goal_set_planner_node-4]     from curobo.wrap.reacher.motion_gen import MotionGenPlanConfig
[cumotion_goal_set_planner_node-4]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/wrap/reacher/motion_gen.py", line 1411, in <module>
[cumotion_goal_set_planner_node-4]     class MotionGen(MotionGenConfig):
[cumotion_goal_set_planner_node-4]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/wrap/reacher/motion_gen.py", line 4189, in MotionGen
[cumotion_goal_set_planner_node-4]     grasp_approach_offset: Pose = Pose.from_list([0, 0, -0.15, 1, 0, 0, 0]),
[cumotion_goal_set_planner_node-4]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/types/math.py", line 228, in from_list
[cumotion_goal_set_planner_node-4]     return Pose(position=position, quaternion=quaternion)
[cumotion_goal_set_planner_node-4]   File "<string>", line 10, in __init__
[cumotion_goal_set_planner_node-4]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/types/math.py", line 85, in __post_init__
[cumotion_goal_set_planner_node-4]     self.quaternion = normalize_quaternion(self.quaternion)
[cumotion_goal_set_planner_node-4] RuntimeError: The following operation failed in the TorchScript interpreter.
[cumotion_goal_set_planner_node-4] Traceback of TorchScript (most recent call last):
[cumotion_goal_set_planner_node-4]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/types/math.py", line 533, in normalize_quaternion
[cumotion_goal_set_planner_node-4] @get_torch_jit_decorator()
[cumotion_goal_set_planner_node-4] def normalize_quaternion(in_quaternion: torch.Tensor) -> torch.Tensor:
[cumotion_goal_set_planner_node-4]     k = torch.sign(in_quaternion[..., 0:1])
[cumotion_goal_set_planner_node-4]         ~~~~~~~~~~ <--- HERE
[cumotion_goal_set_planner_node-4]     # NOTE: torch sign returns 0 as sign value when value is 0.0
[cumotion_goal_set_planner_node-4]     k = torch.where(k == 0, 1.0, k)
[cumotion_goal_set_planner_node-4] RuntimeError: CUDA error: no kernel image is available for execution on the device
[cumotion_goal_set_planner_node-4] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[cumotion_goal_set_planner_node-4] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[cumotion_goal_set_planner_node-4] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
[cumotion_goal_set_planner_node-4] 
[cumotion_goal_set_planner_node-4] 
[ERROR] [robot_segmenter_node-5]: process has died [pid 13596, exit code 1, cmd '/workspaces/isaac_ros-dev/install/isaac_ros_cumotion/lib/isaac_ros_cumotion/robot_segmenter_node --ros-args -r __node:=robot_segmenter -r __ns:=/ -p use_sim_time:=True -p sub_qos:=DEFAULT -p pub_qos:=DEFAULT --params-file /tmp/launch_params_ccr9szi3'].
[ERROR] [cumotion_goal_set_planner_node-4]: process has died [pid 13594, exit code 1, cmd '/workspaces/isaac_ros-dev/install/isaac_ros_cumotion/lib/isaac_ros_cumotion/cumotion_goal_set_planner_node --ros-args -r __node:=cumotion_planner -r __ns:=/ -p use_sim_time:=True -p sub_qos:=DEFAULT -p pub_qos:=DEFAULT --params-file /tmp/launch_params_81tdd0lh'].
[attach_object_server_node-6] /usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:287: UserWarning: 
[attach_object_server_node-6] NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition with CUDA capability sm_120 is not compatible with the current PyTorch installation.
[attach_object_server_node-6] The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
[attach_object_server_node-6] If you want to use the NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
[attach_object_server_node-6] 
[attach_object_server_node-6]   warnings.warn(
[attach_object_server_node-6] Traceback (most recent call last):
[attach_object_server_node-6]   File "/workspaces/isaac_ros-dev/install/isaac_ros_cumotion_object_attachment/lib/isaac_ros_cumotion_object_attachment/attach_object_server_node", line 33, in <module>
[attach_object_server_node-6]     sys.exit(load_entry_point('isaac-ros-cumotion-object-attachment', 'console_scripts', 'attach_object_server_node')())
[attach_object_server_node-6]   File "/workspaces/isaac_ros-dev/install/isaac_ros_cumotion_object_attachment/lib/isaac_ros_cumotion_object_attachment/attach_object_server_node", line 25, in importlib_load_entry_point
[attach_object_server_node-6]     return next(matches).load()
[attach_object_server_node-6]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
[attach_object_server_node-6]     module = import_module(match.group('module'))
[attach_object_server_node-6]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[attach_object_server_node-6]     return _bootstrap._gcd_import(name[level:], package, level)
[attach_object_server_node-6]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[attach_object_server_node-6]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[attach_object_server_node-6]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[attach_object_server_node-6]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[attach_object_server_node-6]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[attach_object_server_node-6]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[attach_object_server_node-6]   File "/workspaces/isaac_ros-dev/build/isaac_ros_cumotion_object_attachment/isaac_ros_cumotion_object_attachment/attach_object_server.py", line 35, in <module>
[attach_object_server_node-6]     from isaac_ros_cumotion.update_kinematics import get_robot_config
[attach_object_server_node-6]   File "/workspaces/isaac_ros-dev/build/isaac_ros_cumotion/isaac_ros_cumotion/__init__.py", line 17, in <module>
[attach_object_server_node-6]     from .cumotion_goal_set_client import CumotionGoalSetClient
[attach_object_server_node-6]   File "/workspaces/isaac_ros-dev/build/isaac_ros_cumotion/isaac_ros_cumotion/cumotion_goal_set_client.py", line 10, in <module>
[attach_object_server_node-6]     from curobo.wrap.reacher.motion_gen import MotionGenPlanConfig
[attach_object_server_node-6]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/wrap/reacher/motion_gen.py", line 1411, in <module>
[attach_object_server_node-6]     class MotionGen(MotionGenConfig):
[attach_object_server_node-6]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/wrap/reacher/motion_gen.py", line 4189, in MotionGen
[attach_object_server_node-6]     grasp_approach_offset: Pose = Pose.from_list([0, 0, -0.15, 1, 0, 0, 0]),
[attach_object_server_node-6]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/types/math.py", line 228, in from_list
[attach_object_server_node-6]     return Pose(position=position, quaternion=quaternion)
[attach_object_server_node-6]   File "<string>", line 10, in __init__
[attach_object_server_node-6]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/types/math.py", line 85, in __post_init__
[attach_object_server_node-6]     self.quaternion = normalize_quaternion(self.quaternion)
[attach_object_server_node-6] RuntimeError: The following operation failed in the TorchScript interpreter.
[attach_object_server_node-6] Traceback of TorchScript (most recent call last):
[attach_object_server_node-6]   File "/workspaces/isaac_ros-dev/build/curobo_core/curobo/src/curobo/types/math.py", line 533, in normalize_quaternion
[attach_object_server_node-6] @get_torch_jit_decorator()
[attach_object_server_node-6] def normalize_quaternion(in_quaternion: torch.Tensor) -> torch.Tensor:
[attach_object_server_node-6]     k = torch.sign(in_quaternion[..., 0:1])
[attach_object_server_node-6]         ~~~~~~~~~~ <--- HERE
[attach_object_server_node-6]     # NOTE: torch sign returns 0 as sign value when value is 0.0
[attach_object_server_node-6]     k = torch.where(k == 0, 1.0, k)
[attach_object_server_node-6] RuntimeError: CUDA error: no kernel image is available for execution on the device
[attach_object_server_node-6] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[attach_object_server_node-6] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[attach_object_server_node-6] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
[attach_object_server_node-6] 
[attach_object_server_node-6] 
[ERROR] [attach_object_server_node-6]: process has died [pid 13598, exit code 1, cmd '/workspaces/isaac_ros-dev/install/isaac_ros_cumotion_object_attachment/lib/isaac_ros_cumotion_object_attachment/attach_object_server_node --ros-args -r __node:=object_attachment -r __ns:=/ -p use_sim_time:=True -p sub_qos:=DEFAULT -p pub_qos:=DEFAULT --params-file /tmp/launch_params_lpg4qykf'].
[component_container_mt-1] I0901 16:56:24.989929 13641 gpu_hash_interface_impl.cuh:83] Creating a GPUHashImpl with requested capacity of 4096 blocks. Real capacity: 4096
[component_container_mt-1] I0901 16:56:24.990041 13641 layer_cake_impl.h:32] Adding Layer with type: N6nvblox15VoxelBlockLayerINS_9TsdfVoxelEEE, voxel_size: 0.01, and memory_type: kDevice to LayerCake.
[component_container_mt-1] I0901 16:56:25.013222 13641 block_memory_pool_impl.h:65] Expanding the memory pool with 2048 blocks. Number of allocated blocks: 2048
[component_container_mt-1] I0901 16:56:25.037250 13641 gpu_hash_interface_impl.cuh:83] Creating a GPUHashImpl with requested capacity of 4096 blocks. Real capacity: 4096
[component_container_mt-1] I0901 16:56:34.779538 13641 layer_cake_impl.h:32] Adding Layer with type: N6nvblox15VoxelBlockLayerINS_10ColorVoxelEEE, voxel_size: 0.01, and memory_type: kDevice to LayerCake.
[component_container_mt-1] I0901 16:56:34.785594 13641 block_memory_pool_impl.h:65] Expanding the memory pool with 2048 blocks. Number of allocated blocks: 2048
[component_container_mt-1] I0901 16:56:34.788118 13641 gpu_hash_interface_impl.cuh:83] Creating a GPUHashImpl with requested capacity of 4096 blocks. Real capacity: 4096
[component_container_mt-1] I0901 16:56:44.518033 13641 layer_cake_impl.h:32] Adding Layer with type: N6nvblox15VoxelBlockLayerINS_14FreespaceVoxelEEE, voxel_size: 0.01, and memory_type: kDevice to LayerCake.
[component_container_mt-1] I0901 16:56:44.522979 13641 block_memory_pool_impl.h:65] Expanding the memory pool with 2048 blocks. Number of allocated blocks: 2048
[component_container_mt-1] I0901 16:56:44.547658 13641 gpu_hash_interface_impl.cuh:83] Creating a GPUHashImpl with requested capacity of 4096 blocks. Real capacity: 4096
[component_container_mt-1] I0901 16:56:54.334323 13641 layer_cake_impl.h:32] Adding Layer with type: N6nvblox15VoxelBlockLayerINS_14OccupancyVoxelEEE, voxel_size: 0.01, and memory_type: kDevice to LayerCake.
[component_container_mt-1] I0901 16:56:54.341023 13641 block_memory_pool_impl.h:65] Expanding the memory pool with 2048 blocks. Number of allocated blocks: 2048
[component_container_mt-1] I0901 16:56:54.881120 13641 gpu_hash_interface_impl.cuh:83] Creating a GPUHashImpl with requested capacity of 4096 blocks. Real capacity: 4096
[component_container_mt-1] I0901 16:56:54.881224 13641 layer_cake_impl.h:32] Adding Layer with type: N6nvblox15VoxelBlockLayerINS_9EsdfVoxelEEE, voxel_size: 0.01, and memory_type: kDevice to LayerCake.
[component_container_mt-1] I0901 16:56:54.881376 13641 block_memory_pool_impl.h:65] Expanding the memory pool with 2048 blocks. Number of allocated blocks: 2048
[component_container_mt-1] I0901 16:56:54.881891 13641 gpu_hash_interface_impl.cuh:83] Creating a GPUHashImpl with requested capacity of 4096 blocks. Real capacity: 4096
[component_container_mt-1] I0901 16:56:54.881947 13641 layer_cake_impl.h:32] Adding Layer with type: N6nvblox10BlockLayerINS_9MeshBlockEEE, voxel_size: 0.01, and memory_type: kDevice to LayerCake.
[component_container_mt-1] I0901 16:56:54.881956 13641 layer_cake_streamer_impl.h:79] Adding Streamer with type: N6nvblox25LayerStreamerOldestBlocksINS_15VoxelBlockLayerINS_9TsdfVoxelEEEEE to LayerCake.
[component_container_mt-1] I0901 16:56:54.881960 13641 layer_cake_streamer_impl.h:79] Adding Streamer with type: N6nvblox25LayerStreamerOldestBlocksINS_15VoxelBlockLayerINS_10ColorVoxelEEEEE to LayerCake.
[component_container_mt-1] I0901 16:56:54.881963 13641 layer_cake_streamer_impl.h:79] Adding Streamer with type: N6nvblox25LayerStreamerOldestBlocksINS_15VoxelBlockLayerINS_14FreespaceVoxelEEEEE to LayerCake.
[component_container_mt-1] I0901 16:56:54.881965 13641 layer_cake_streamer_impl.h:79] Adding Streamer with type: N6nvblox25LayerStreamerOldestBlocksINS_15VoxelBlockLayerINS_14OccupancyVoxelEEEEE to LayerCake.
[component_container_mt-1] I0901 16:56:54.881968 13641 layer_cake_streamer_impl.h:79] Adding Streamer with type: N6nvblox25LayerStreamerOldestBlocksINS_15VoxelBlockLayerINS_9EsdfVoxelEEEEE to LayerCake.
[component_container_mt-1] I0901 16:56:54.881975 13641 layer_cake_streamer_impl.h:79] Adding Streamer with type: N6nvblox25LayerStreamerOldestBlocksINS_10BlockLayerINS_9MeshBlockEEEEE to LayerCake.
[component_container_mt-1] I0901 16:56:54.888931 13641 block_memory_pool_impl.h:65] Expanding the memory pool with 2048 blocks. Number of allocated blocks: 2048
[component_container_mt-1] I0901 16:56:54.890353 13641 gpu_hash_interface_impl.cuh:83] Creating a GPUHashImpl with requested capacity of 4096 blocks. Real capacity: 4096
[component_container_mt-1] I0901 16:56:54.890656 13641 layer_cake_impl.h:32] Adding Layer with type: N6nvblox15VoxelBlockLayerINS_9TsdfVoxelEEE, voxel_size: 0.01, and memory_type: kDevice to LayerCake.
[component_container_mt-1] I0901 16:56:54.896210 13641 block_memory_pool_impl.h:65] Expanding the memory pool with 2048 blocks. Number of allocated blocks: 2048
[component_container_mt-1] I0901 16:56:54.915287 13641 gpu_hash_interface_impl.cuh:83] Creating a GPUHashImpl with requested capacity of 4096 blocks. Real capacity: 4096
[component_container_mt-1] I0901 16:56:54.918738 13641 layer_cake_impl.h:32] Adding Layer with type: N6nvblox15VoxelBlockLayerINS_10ColorVoxelEEE, voxel_size: 0.01, and memory_type: kDevice to LayerCake.
[component_container_mt-1] I0901 16:56:54.927114 13641 block_memory_pool_impl.h:65] Expanding the memory pool with 2048 blocks. Number of allocated blocks: 2048
[component_container_mt-1] I0901 16:56:54.933459 13641 gpu_hash_interface_impl.cuh:83] Creating a GPUHashImpl with requested capacity of 4096 blocks. Real capacity: 4096
[component_container_mt-1] I0901 16:56:54.933560 13641 layer_cake_impl.h:32] Adding Layer with type: N6nvblox15VoxelBlockLayerINS_14FreespaceVoxelEEE, voxel_size: 0.01, and memory_type: kDevice to LayerCake.
[component_container_mt-1] I0901 16:56:54.938212 13641 block_memory_pool_impl.h:65] Expanding the memory pool with 2048 blocks. Number of allocated blocks: 2048
[component_container_mt-1] I0901 16:56:54.941313 13641 gpu_hash_interface_impl.cuh:83] Creating a GPUHashImpl with requested capacity of 4096 blocks. Real capacity: 4096
[component_container_mt-1] I0901 16:56:54.941381 13641 layer_cake_impl.h:32] Adding Layer with type: N6nvblox15VoxelBlockLayerINS_14OccupancyVoxelEEE, voxel_size: 0.01, and memory_type: kDevice to LayerCake.
[component_container_mt-1] I0901 16:56:54.947036 13641 block_memory_pool_impl.h:65] Expanding the memory pool with 2048 blocks. Number of allocated blocks: 2048
[component_container_mt-1] I0901 16:56:54.969519 13641 gpu_hash_interface_impl.cuh:83] Creating a GPUHashImpl with requested capacity of 4096 blocks. Real capacity: 4096
[component_container_mt-1] I0901 16:56:54.972791 13641 layer_cake_impl.h:32] Adding Layer with type: N6nvblox15VoxelBlockLayerINS_9EsdfVoxelEEE, voxel_size: 0.01, and memory_type: kDevice to LayerCake.
[component_container_mt-1] I0901 16:56:54.972918 13641 block_memory_pool_impl.h:65] Expanding the memory pool with 2048 blocks. Number of allocated blocks: 2048
[component_container_mt-1] I0901 16:56:54.980288 13641 gpu_hash_interface_impl.cuh:83] Creating a GPUHashImpl with requested capacity of 4096 blocks. Real capacity: 4096
[component_container_mt-1] I0901 16:56:54.980391 13641 layer_cake_impl.h:32] Adding Layer with type: N6nvblox10BlockLayerINS_9MeshBlockEEE, voxel_size: 0.01, and memory_type: kDevice to LayerCake.
[component_container_mt-1] I0901 16:56:54.980402 13641 layer_cake_streamer_impl.h:79] Adding Streamer with type: N6nvblox25LayerStreamerOldestBlocksINS_15VoxelBlockLayerINS_9TsdfVoxelEEEEE to LayerCake.
[component_container_mt-1] I0901 16:56:54.980404 13641 layer_cake_streamer_impl.h:79] Adding Streamer with type: N6nvblox25LayerStreamerOldestBlocksINS_15VoxelBlockLayerINS_10ColorVoxelEEEEE to LayerCake.
[component_container_mt-1] I0901 16:56:54.980406 13641 layer_cake_streamer_impl.h:79] Adding Streamer with type: N6nvblox25LayerStreamerOldestBlocksINS_15VoxelBlockLayerINS_14FreespaceVoxelEEEEE to LayerCake.
[component_container_mt-1] I0901 16:56:54.980409 13641 layer_cake_streamer_impl.h:79] Adding Streamer with type: N6nvblox25LayerStreamerOldestBlocksINS_15VoxelBlockLayerINS_14OccupancyVoxelEEEEE to LayerCake.
[component_container_mt-1] I0901 16:56:54.980410 13641 layer_cake_streamer_impl.h:79] Adding Streamer with type: N6nvblox25LayerStreamerOldestBlocksINS_15VoxelBlockLayerINS_9EsdfVoxelEEEEE to LayerCake.
[component_container_mt-1] I0901 16:56:54.980413 13641 layer_cake_streamer_impl.h:79] Adding Streamer with type: N6nvblox25LayerStreamerOldestBlocksINS_10BlockLayerINS_9MeshBlockEEEEE to LayerCake.
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/nvblox_node' in container 'manipulator_container'

--
Best regards,

**Comment by swapnesh-wani-nvidia** [comment]
Hello,

From the error, it looks like the ros2-control node is crashing. Could you share the versions of the following packages?

```
ros-jazzy-ros2-control
ros-jazzy-controller-manager
ros-jazzy-controller-interface
ros-jazzy-hardware-interface
```

**Comment by mat-macnica** [comment]
Hello,

Thank you very much for your kindness.
I really appreciate your help.
 
I'd like to share version info.

  <name>ros2_control</name>
  <version>4.39.2</version>

  <name>controller_manager</name>
  <version>4.39.2</version>

  <name>controller_interface</name>
  <version>4.38.0</version>

  <name>hardware_interface</name>
  <version>4.38.0</version>

 I would appreciate if you check the behavior with RTX-Pro6000 GPU & tell us how to solve this problem.
--
Best regards

**Comment by karanchahal-nv** [comment]
This works for me:

```
admin@karan-Precision-5820-Tower-X-Series:/workspaces/isaac_ros-dev/ros_ws$ sudo apt policy ros-jazzy-ros2-control
ros-jazzy-ros2-control:
  Installed: (none)
  Candidate: 4.39.2-1noble.20251110.161902
  Version table:
     4.39.2-1noble.20251110.161902 500
        500 http://packages.ros.org/ros2/ubuntu noble/main amd64 Packages
admin@karan-Precision-5820-Tower-X-Series:/workspaces/isaac_ros-dev/ros_ws$ sudo apt policy ros-jazzy-controller-manager
ros-jazzy-controller-manager:
  Installed: 4.39.2-1noble.20251110.161104
  Candidate: 4.39.2-1noble.20251110.161104
  Version table:
 *** 4.39.2-1noble.20251110.161104 500
        500 http://packages.ros.org/ros2/ubuntu noble/main amd64 Packages
        100 /var/lib/dpkg/status
admin@karan-Precision-5820-Tower-X-Series:/workspaces/isaac_ros-dev/ros_ws$ sudo apt policy ros-jazzy-controller-interface
ros-jazzy-controller-interface:
  Installed: 4.39.2-1noble.20251110.160627
  Candidate: 4.39.2-1noble.20251110.160627
  Version table:
 *** 4.39.2-1noble.20251110.160627 500
        500 http://packages.ros.org/ros2/ubuntu noble/main amd64 Packages
        100 /var/lib/dpkg/status
admin@karan-Precision-5820-Tower-X-Series:/workspaces/isaac_ros-dev/ros_ws$ sudo apt policy ros-jazzy-hardware-interface
ros-jazzy-hardware-interface:
  Installed: 4.39.2-1noble.20251110.155623
  Candidate: 4.39.2-1noble.20251110.155623
  Version table:
 *** 4.39.2-1noble.20251110.155623 500
        500 http://packages.ros.org/ros2/ubuntu noble/main amd64 Packages
        100 /var/lib/dpkg/status
```

If you dont have the same version across these packages, things will likely break, please upgrade your drivers.
